### ISSUE TITLE
Kvalitativa prover visas inte som 1-5

### ISSUE THREAD

**Issue by MariaKarlberg** [planktontoolbox/plankton-toolbox#74]
![Gamla PTBX](https://user-images.githubusercontent.com/43179262/107206813-d4a39780-69ff-11eb-9325-7f9abcfba73f.jpg)
![Nya PTBX](https://user-images.githubusercontent.com/43179262/107206817-d53c2e00-69ff-11eb-85e2-978e71070b3e.jpg)

I nya versionen står det qualitative i listan där man ser vad man har räknat, istf 1-5. Vill man veta hur många man räknat får man markera arten och titta till vänster. Se det gulmarkerade i ena bilden. Hur det såg ut i gamla PTBX visas i andra bilden.

**Comment by arnoldandreasson** [comment]
Ready for test.
